import Header from '@/app/components/Header';
import Sidebar from '@/app/components/Sidebar';
import { getDocuments } from '@/lib/doc';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const allDocuments = getDocuments();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header docs={allDocuments} />
        <div className="flex">
          <Sidebar docs={allDocuments} />
          <main className="container mx-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
